### PR TITLE
[PR-9050] On failed devise login Talkable middleware was not loaded.

### LINKED ISSUE #20: API call register_affiliate_member fails
The generator adds this code to the Application Controller *app/controllers/application_controller.rb*:
```
class ApplicationController < ActionController::Base
  before_action :load_talkable_offer

  protected

  def load_talkable_offer
    origin = Talkable.register_affiliate_member
    @offer ||= origin.offer if origin
  end
end
```

`Talkable.register_affiliate_member` fails with the error:
```
Talkable::API::BadRequest at /users/sign_in
Either email or visitor must be present.
```

### PR DESCRIPTION
**Pull request by antonpaisov**
fixes #20 
here's a list of rails default middlewares, I've decided to add `Talkable::Middleware` right after the last one, this way it will always load before `Warden::Manager` no matter if it's present or not.

### CODE REVIEW

File: lib/talkable/railtie.rb [hunk 1]
```diff
@@ -5,7 +5,7 @@ class Railtie < Rails::Railtie
     end
 
     initializer "talkable.add_middleware" do |app|
-      app.middleware.use Talkable::Middleware
+      app.middleware.insert_after Rack::TempfileReaper, Talkable::Middleware
```
Comment (zhuravel) [inline lib/talkable/railtie.rb]: You sure this middleware is always present? I don’t see it in our list.
<details>

```sh
$ rails middleware
use Webpacker::DevServerProxy
use UTF8Cleaner::Middleware
use Rack::Sendfile
use ActionDispatch::Static
use ActionDispatch::Executor
use Rack::Rewrite
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use RequestStore::Middleware
use ActionDispatch::RemoteIp
use HandleUnknownHttpMethod
use Sprockets::Rails::QuietAssets
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use Bugsnag::Rack
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use RequestFilter
use EtagCaching
use ThrottlingMiddleware
run Talkable::Application.routes
```

</details>

Comment (antonpaisov) [reply lib/talkable/railtie.rb]: Indeed we don't, interesting.
Originally I wanted to add an `if` that would check if `Warden::Manager` is present and if so our middleware will be added before warden, otherwise add it the old way.
But I haven't found a good way to perform this check. Maybe anyone has any ideas about that?
Or maybe we should just pick a different default middleware to add `Talkable::Middleware` after?

Comment (antonpaisov) [reply lib/talkable/railtie.rb]: so far `Rack::ETag` seems to be a good candidate to hook to.

File: README.md [hunk 2]
```diff
@@ -98,12 +98,26 @@ For security, you should set these configuration variables from the Unix environ
...
+
+Here's how you can add Talkable middleware manually.
+
 ```ruby
 class Application < Rails::Application
   config.middleware.use Talkable::Middleware
 end
 ```
 
+If you're using devise, it's importand to load Talkable middleware before `Warden::Manager`.
```
Comment (zhuravel) [inline README.md]: devise → Devise
importand → important

File: lib/talkable/railtie.rb (hunk 1 above)
Comment (vitalikdanchenko) [reply lib/talkable/railtie.rb]: lets use `defined?(::Warden::Manager)` in order to explicitly specify the order of middlewares

**Review by vitalikdanchenko — APPROVED** [review]
LGTM
